name: 'Thank You Action'
description: '...'
author: 'Fede'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'